import CbsLean.MagicCapacitySemigroup
import Mathlib.Data.Nat.ModEq

namespace CbsLean
namespace MagicCapacity

/-!
# Exact characterization in the coprime endpoint case

This module is exploratory.  It proves the converse to the two-generator
sufficiency theorem when the endpoint widths are coprime.  The proof uses one
universal residue witness `q*x ≡ -1 (mod p)` and one Apéry-style residue witness
`q*j ≡ h (mod p)`.
-/

/-- Exact insertion at every source index. -/
def GloballyExactInsertion
    (sourceWidth middleWidth targetWidth : ℕ) : Prop :=
  ∀ x,
    insertionComposite sourceWidth middleWidth targetWidth x =
      indexLift sourceWidth targetWidth x

/-- A two-generator middle width is globally exact. -/
theorem globallyExactInsertion_of_mem_twoGeneratorSemigroup
    {sourceWidth middleWidth targetWidth : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddle : 0 < middleWidth)
    (hmem : InTwoGeneratorSemigroup
      sourceWidth targetWidth middleWidth) :
    GloballyExactInsertion sourceWidth middleWidth targetWidth := by
  intro x
  exact insertionComposite_eq_direct_of_mem_twoGeneratorSemigroup
    hsource hmiddle hmem

/--
If `targetWidth*x + residual = sourceWidth*y`, with a residual strictly below
one source width, then `y` is exactly the ceiling lift.
-/
theorem indexLift_eq_of_mul_add_eq
    {sourceWidth targetWidth x residual y : ℕ}
    (hsource : 0 < sourceWidth)
    (hresidual : residual < sourceWidth)
    (heq : targetWidth * x + residual = sourceWidth * y) :
    indexLift sourceWidth targetWidth x = y := by
  apply Nat.le_antisymm
  · apply (indexLift_le_iff hsource).2
    omega
  · by_contra hnot
    have hlt : indexLift sourceWidth targetWidth x < y :=
      Nat.lt_of_not_ge hnot
    have hsucc : indexLift sourceWidth targetWidth x + 1 ≤ y :=
      Nat.succ_le_iff.mpr hlt
    have hmul := Nat.mul_le_mul_left sourceWidth hsucc
    have hmul' :
        sourceWidth * indexLift sourceWidth targetWidth x + sourceWidth ≤
          sourceWidth * y := by
      simpa [Nat.mul_add] using hmul
    have hspec :
        targetWidth * x ≤
          sourceWidth * indexLift sourceWidth targetWidth x :=
      indexLift_spec
        (sourceWidth := sourceWidth)
        (targetWidth := targetWidth)
        (x := x) hsource
    omega

/--
For coprime positive endpoint widths with `sourceWidth > 1`, choose the unique
kind of source residue at which the direct lift has residual one.
-/
theorem exists_negativeOneLiftWitness
    {sourceWidth targetWidth : ℕ}
    (hcoprime : Nat.Coprime sourceWidth targetWidth)
    (hsource : 1 < sourceWidth) :
    ∃ x z : ℕ,
      x < sourceWidth ∧
      targetWidth * x ≡ sourceWidth - 1 [MOD sourceWidth] ∧
      targetWidth * x + 1 = sourceWidth * z := by
  obtain ⟨x, hxlt, hxmod⟩ :=
    Nat.exists_mul_mod_eq_of_coprime
      (r := sourceWidth - 1)
      hcoprime.symm
      (by omega : sourceWidth ≠ 0)
  have hpredlt : sourceWidth - 1 < sourceWidth := by omega
  have hxmodeq :
      targetWidth * x ≡ sourceWidth - 1 [MOD sourceWidth] := by
    simpa [Nat.ModEq, Nat.mod_eq_of_lt hpredlt] using hxmod
  have hzero :
      targetWidth * x + 1 ≡ 0 [MOD sourceWidth] := by
    calc
      targetWidth * x + 1 ≡ (sourceWidth - 1) + 1 [MOD sourceWidth] :=
        hxmodeq.add_right 1
      _ = sourceWidth := by omega
      _ ≡ 0 [MOD sourceWidth] := Nat.modulus_modEq_zero
  obtain ⟨z, hz⟩ := (Nat.modEq_zero_iff_dvd.mp hzero)
  exact ⟨x, z, hxlt, hxmodeq, hz⟩

/-- Every residue has a representative in the target-generated Apéry row. -/
theorem exists_targetResidueWitness
    {sourceWidth middleWidth targetWidth : ℕ}
    (hcoprime : Nat.Coprime sourceWidth targetWidth)
    (hsource : 0 < sourceWidth) :
    ∃ j : ℕ,
      j < sourceWidth ∧
      targetWidth * j ≡ middleWidth [MOD sourceWidth] := by
  obtain ⟨j, hjlt, hjmod⟩ :=
    Nat.exists_mul_mod_eq_of_coprime
      (r := middleWidth)
      hcoprime.symm
      (Nat.ne_of_gt hsource)
  exact ⟨j, hjlt, hjmod⟩

/--
Coprime converse: global exactness forces the middle width into the additive
semigroup generated by the endpoint widths.
-/
theorem mem_twoGeneratorSemigroup_of_globallyExactInsertion_of_coprime
    {sourceWidth middleWidth targetWidth : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddle : 0 < middleWidth)
    (hcoprime : Nat.Coprime sourceWidth targetWidth)
    (hexact : GloballyExactInsertion
      sourceWidth middleWidth targetWidth) :
    InTwoGeneratorSemigroup sourceWidth targetWidth middleWidth := by
  by_cases hone : sourceWidth = 1
  · subst sourceWidth
    refine ⟨middleWidth, 0, ?_⟩
    simp
  have hsourceOne : 1 < sourceWidth := by omega
  obtain ⟨x, z, hxlt, hxmodeq, hxz⟩ :=
    exists_negativeOneLiftWitness hcoprime hsourceOne
  obtain ⟨j, hjlt, hjmodeq⟩ :=
    exists_targetResidueWitness
      (middleWidth := middleWidth) hcoprime hsource
  have hproduct :
      middleWidth * x ≡ (sourceWidth - 1) * j [MOD sourceWidth] := by
    have hleft :
        middleWidth * x ≡ (targetWidth * j) * x [MOD sourceWidth] :=
      (hjmodeq.mul_right x).symm
    have hright :
        (targetWidth * j) * x ≡ (sourceWidth - 1) * j [MOD sourceWidth] := by
      simpa [Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm] using
        hxmodeq.mul_right j
    exact hleft.trans hright
  have hresidualZero :
      middleWidth * x + j ≡ 0 [MOD sourceWidth] := by
    have hsum := hproduct.add_right j
    have hcollapse : (sourceWidth - 1) * j + j = sourceWidth * j := by
      calc
        (sourceWidth - 1) * j + j =
            ((sourceWidth - 1) + 1) * j := by ring
        _ = sourceWidth * j := by
          rw [Nat.sub_add_cancel (by omega)]
    have hmultiple : sourceWidth * j ≡ 0 [MOD sourceWidth] :=
      (Nat.dvd_mul_right sourceWidth j).modEq_zero_nat
    rw [hcollapse] at hsum
    exact hsum.trans hmultiple
  obtain ⟨y, hy⟩ :=
    Nat.modEq_zero_iff_dvd.mp hresidualZero
  have hliftTarget : indexLift sourceWidth targetWidth x = z :=
    indexLift_eq_of_mul_add_eq
      hsource (by omega) hxz
  have hliftMiddle : indexLift sourceWidth middleWidth x = y :=
    indexLift_eq_of_mul_add_eq
      hsource hjlt hy
  have hcomposite : indexLift middleWidth targetWidth y = z := by
    have h := hexact x
    rw [insertionComposite, hliftMiddle, hliftTarget] at h
    exact h
  have houter : targetWidth * y ≤ middleWidth * z := by
    have hspec :=
      indexLift_spec
        (sourceWidth := middleWidth)
        (targetWidth := targetWidth)
        (x := y) hmiddle
    rw [hcomposite] at hspec
    exact hspec
  have hscaled := Nat.mul_le_mul_left sourceWidth houter
  have hcomparison :
      targetWidth * (middleWidth * x + j) ≤
        middleWidth * (targetWidth * x + 1) := by
    calc
      targetWidth * (middleWidth * x + j) =
          sourceWidth * (targetWidth * y) := by
        rw [hy]
        ring
      _ ≤ sourceWidth * (middleWidth * z) := hscaled
      _ = middleWidth * (targetWidth * x + 1) := by
        rw [hxz]
        ring
  have htargetj : targetWidth * j ≤ middleWidth := by
    have hnormalized :
        targetWidth * j + targetWidth * middleWidth * x ≤
          middleWidth + targetWidth * middleWidth * x := by
      simpa [Nat.mul_add, Nat.add_mul, Nat.mul_assoc,
        Nat.mul_comm, Nat.mul_left_comm] using hcomparison
    exact Nat.le_of_add_le_add_right hnormalized
  have hdifference :
      sourceWidth ∣ middleWidth - targetWidth * j :=
    (Nat.modEq_iff_dvd' htargetj).1 hjmodeq
  obtain ⟨a, ha⟩ := hdifference
  refine ⟨a, j, ?_⟩
  calc
    middleWidth =
        (middleWidth - targetWidth * j) + targetWidth * j :=
      (Nat.sub_add_cancel htargetj).symm
    _ = sourceWidth * a + targetWidth * j := by rw [ha]
    _ = a * sourceWidth + j * targetWidth := by ring

/-- Exact iff semigroup membership for coprime positive endpoints. -/
theorem globallyExactInsertion_iff_mem_twoGeneratorSemigroup_of_coprime
    {sourceWidth middleWidth targetWidth : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddle : 0 < middleWidth)
    (hcoprime : Nat.Coprime sourceWidth targetWidth) :
    GloballyExactInsertion sourceWidth middleWidth targetWidth ↔
      InTwoGeneratorSemigroup sourceWidth targetWidth middleWidth := by
  constructor
  · exact mem_twoGeneratorSemigroup_of_globallyExactInsertion_of_coprime
      hsource hmiddle hcoprime
  · exact globallyExactInsertion_of_mem_twoGeneratorSemigroup
      hsource hmiddle

end MagicCapacity
end CbsLean
