import CbsLean.MagicCapacity

namespace CbsLean
namespace MagicCapacity

/-!
# Two-generator exactness for magic-capacity insertion

This module strengthens the basic divisibility exactness law.  A middle width
need not be a multiple of either endpoint individually: every nonnegative
combination of the source and target widths gives exact insertion.
-/

/-- Membership in the additive semigroup generated by two endpoint widths. -/
def InTwoGeneratorSemigroup
    (sourceWidth targetWidth middleWidth : ℕ) : Prop :=
  ∃ a b : ℕ,
    middleWidth = a * sourceWidth + b * targetWidth

/--
If the middle width is `a * sourceWidth + b * targetWidth`, its first-stage
lift is bounded by `a` exact source blocks plus `b` direct target lifts.
-/
theorem indexLift_middle_le_twoGeneratorBound
    {sourceWidth middleWidth targetWidth x a b : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddleRep :
      middleWidth = a * sourceWidth + b * targetWidth) :
    indexLift sourceWidth middleWidth x ≤
      a * x + b * indexLift sourceWidth targetWidth x := by
  apply (indexLift_le_iff hsource).2
  rw [hmiddleRep]
  have hdirect :
      targetWidth * x ≤
        sourceWidth * indexLift sourceWidth targetWidth x :=
    indexLift_spec
      (sourceWidth := sourceWidth)
      (targetWidth := targetWidth)
      (x := x) hsource
  have hb := Nat.mul_le_mul_left b hdirect
  calc
    (a * sourceWidth + b * targetWidth) * x =
        sourceWidth * (a * x) + b * (targetWidth * x) := by ring
    _ ≤ sourceWidth * (a * x) +
        b * (sourceWidth * indexLift sourceWidth targetWidth x) :=
      Nat.add_le_add_left hb _
    _ = sourceWidth *
        (a * x + b * indexLift sourceWidth targetWidth x) := by ring

/--
Two-generator sufficiency theorem: if the inserted width lies in the additive
semigroup generated by the endpoint widths, ceiling refinement composes
exactly for every index.
-/
theorem insertionComposite_eq_direct_of_twoGenerator
    {sourceWidth middleWidth targetWidth x a b : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddle : 0 < middleWidth)
    (hmiddleRep :
      middleWidth = a * sourceWidth + b * targetWidth) :
    insertionComposite sourceWidth middleWidth targetWidth x =
      indexLift sourceWidth targetWidth x := by
  apply Nat.le_antisymm
  · apply (indexLift_le_iff hmiddle).2
    have hinner :
        indexLift sourceWidth middleWidth x ≤
          a * x + b * indexLift sourceWidth targetWidth x :=
      indexLift_middle_le_twoGeneratorBound hsource hmiddleRep
    have hinnerScaled := Nat.mul_le_mul_left targetWidth hinner
    have hdirect :
        targetWidth * x ≤
          sourceWidth * indexLift sourceWidth targetWidth x :=
      indexLift_spec
        (sourceWidth := sourceWidth)
        (targetWidth := targetWidth)
        (x := x) hsource
    have ha := Nat.mul_le_mul_left a hdirect
    calc
      targetWidth * indexLift sourceWidth middleWidth x ≤
          targetWidth *
            (a * x + b * indexLift sourceWidth targetWidth x) :=
        hinnerScaled
      _ = a * (targetWidth * x) +
          b * (targetWidth * indexLift sourceWidth targetWidth x) := by ring
      _ ≤ a * (sourceWidth * indexLift sourceWidth targetWidth x) +
          b * (targetWidth * indexLift sourceWidth targetWidth x) :=
        Nat.add_le_add_right ha _
      _ = (a * sourceWidth + b * targetWidth) *
          indexLift sourceWidth targetWidth x := by ring
      _ = middleWidth * indexLift sourceWidth targetWidth x := by
        rw [hmiddleRep]
  · exact indexLift_le_insertionComposite hsource hmiddle

/-- Predicate-packaged form of the two-generator sufficiency theorem. -/
theorem insertionComposite_eq_direct_of_mem_twoGeneratorSemigroup
    {sourceWidth middleWidth targetWidth x : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddle : 0 < middleWidth)
    (hmem : InTwoGeneratorSemigroup
      sourceWidth targetWidth middleWidth) :
    insertionComposite sourceWidth middleWidth targetWidth x =
      indexLift sourceWidth targetWidth x := by
  rcases hmem with ⟨a, b, hmiddleRep⟩
  exact insertionComposite_eq_direct_of_twoGenerator
    hsource hmiddle hmiddleRep

/-- Every two-generator middle width is carry-free. -/
theorem insertionDefect_eq_zero_of_mem_twoGeneratorSemigroup
    {sourceWidth middleWidth targetWidth x : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddle : 0 < middleWidth)
    (hmem : InTwoGeneratorSemigroup
      sourceWidth targetWidth middleWidth) :
    insertionDefect sourceWidth middleWidth targetWidth x = 0 := by
  apply (insertionDefect_eq_zero_iff hsource hmiddle).2
  exact insertionComposite_eq_direct_of_mem_twoGeneratorSemigroup
    hsource hmiddle hmem

/-- A target-divisible middle width is a special two-generator case. -/
theorem insertionComposite_eq_direct_of_target_dvd_middle
    {sourceWidth middleWidth targetWidth x : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddle : 0 < middleWidth)
    (htargetMiddle : targetWidth ∣ middleWidth) :
    insertionComposite sourceWidth middleWidth targetWidth x =
      indexLift sourceWidth targetWidth x := by
  rcases htargetMiddle with ⟨b, hmiddleRep⟩
  apply insertionComposite_eq_direct_of_twoGenerator
    (a := 0) (b := b) hsource hmiddle
  calc
    middleWidth = targetWidth * b := hmiddleRep
    _ = 0 * sourceWidth + b * targetWidth := by
      simp [Nat.mul_comm]

/-- A target-divisible middle width is carry-free. -/
theorem insertionDefect_eq_zero_of_target_dvd_middle
    {sourceWidth middleWidth targetWidth x : ℕ}
    (hsource : 0 < sourceWidth)
    (hmiddle : 0 < middleWidth)
    (htargetMiddle : targetWidth ∣ middleWidth) :
    insertionDefect sourceWidth middleWidth targetWidth x = 0 := by
  apply (insertionDefect_eq_zero_iff hsource hmiddle).2
  exact insertionComposite_eq_direct_of_target_dvd_middle
    hsource hmiddle htargetMiddle

end MagicCapacity
end CbsLean
